<% 
   test = "exec sp_AddDLK_M_JenisBarang 'DTR 130 MD GR',''
exec sp_AddDLK_M_JenisBarang 'D BMP',''
exec sp_AddDLK_M_JenisBarang 'DTR FS LH',''
exec sp_AddDLK_M_JenisBarang 'DTR FS RH',''
exec sp_AddDLK_M_JenisBarang 'DTR FSLH',''
exec sp_AddDLK_M_JenisBarang 'DTR FP',''
exec sp_AddDLK_M_JenisBarang 'DTR PA',''
exec sp_AddDLK_M_JenisBarang 'DTR DL',''
exec sp_AddDLK_M_JenisBarang 'PLR KBN',''
exec sp_AddDLK_M_JenisBarang 'D PBD RH',''
exec sp_AddDLK_M_JenisBarang 'D PBD LH',''
exec sp_AddDLK_M_JenisBarang 'D AS K',''
exec sp_AddDLK_M_JenisBarang 'GRN RH',''
exec sp_AddDLK_M_JenisBarang 'KKP RH',''
exec sp_AddDLK_M_JenisBarang 'KKP LH',''
exec sp_AddDLK_M_JenisBarang 'DT HL',''
exec sp_AddDLK_M_JenisBarang 'HL LH',''
exec sp_AddDLK_M_JenisBarang 'KK ES',''
exec sp_AddDLK_M_JenisBarang 'VC R/L',''
exec sp_AddDLK_M_JenisBarang 'LH KF40',''
exec sp_AddDLK_M_JenisBarang 'KKF 40',''
exec sp_AddDLK_M_JenisBarang 'UDG',''
exec sp_AddDLK_M_JenisBarang 'UDG KCL',''
exec sp_AddDLK_M_JenisBarang 'C16',''
exec sp_AddDLK_M_JenisBarang 'FU',''
exec sp_AddDLK_M_JenisBarang 'DS',''
exec sp_AddDLK_M_JenisBarang 'KA',''
exec sp_AddDLK_M_JenisBarang 'FM',''
exec sp_AddDLK_M_JenisBarang 'LKAL',''
exec sp_AddDLK_M_JenisBarang 'LKAD',''
exec sp_AddDLK_M_JenisBarang 'TBD',''
exec sp_AddDLK_M_JenisBarang 'TBB',''
exec sp_AddDLK_M_JenisBarang 'KRT L300',''
exec sp_AddDLK_M_JenisBarang 'TF K2',''
exec sp_AddDLK_M_JenisBarang '8',''
exec sp_AddDLK_M_JenisBarang 'AS 8MM',''
exec sp_AddDLK_M_JenisBarang 'NP 12',''
exec sp_AddDLK_M_JenisBarang '4 FS',''
exec sp_AddDLK_M_JenisBarang 'PLS 6 FS',''
exec sp_AddDLK_M_JenisBarang 'PLS 6 FS 2',''
exec sp_AddDLK_M_JenisBarang '8 FS',''
exec sp_AddDLK_M_JenisBarang '8 FS 2',''
exec sp_AddDLK_M_JenisBarang 'PLS 10 FS',''
exec sp_AddDLK_M_JenisBarang 'PLS 12 FS',''
exec sp_AddDLK_M_JenisBarang 'BHL PLS 16',''
exec sp_AddDLK_M_JenisBarang 'BHL PLS 16 2',''
exec sp_AddDLK_M_JenisBarang 'BHL PLS 16 3',''
exec sp_AddDLK_M_JenisBarang 'BHL PLS 16 4',''
exec sp_AddDLK_M_JenisBarang 'BHL PLS 16 5',''
exec sp_AddDLK_M_JenisBarang '50 2.2',''
exec sp_AddDLK_M_JenisBarang '50',''
exec sp_AddDLK_M_JenisBarang '65 2.5',''
exec sp_AddDLK_M_JenisBarang '65 2.5 2',''
exec sp_AddDLK_M_JenisBarang '80 2.8',''
exec sp_AddDLK_M_JenisBarang '100',''
exec sp_AddDLK_M_JenisBarang '100 2',''
exec sp_AddDLK_M_JenisBarang '120',''
exec sp_AddDLK_M_JenisBarang '150',''
exec sp_AddDLK_M_JenisBarang '100X50X2.3',''
exec sp_AddDLK_M_JenisBarang 'H3/4X1.5',''
exec sp_AddDLK_M_JenisBarang 'SM 3/4X3 SCH 40',''
exec sp_AddDLK_M_JenisBarang 'SCH 160 3/4"',''
exec sp_AddDLK_M_JenisBarang 'SCH 160 3/4" 2',''
exec sp_AddDLK_M_JenisBarang 'SCH 160 3/4" 3',''
exec sp_AddDLK_M_JenisBarang 'SCH 160 3/4" 4',''
exec sp_AddDLK_M_JenisBarang 'H3/4XSCH40',''
exec sp_AddDLK_M_JenisBarang 'H 3/4 SCH 160',''
exec sp_AddDLK_M_JenisBarang 'H 2" SCH 40',''
exec sp_AddDLK_M_JenisBarang 'SM 2" SCH 40',''
exec sp_AddDLK_M_JenisBarang 'G 3/4X1.7',''
exec sp_AddDLK_M_JenisBarang 'G 1/2X2.6',''
exec sp_AddDLK_M_JenisBarang 'G 1/2X2.6 2',''
exec sp_AddDLK_M_JenisBarang 'SM 1/2 SCH 40',''
exec sp_AddDLK_M_JenisBarang 'PB 14',''
exec sp_AddDLK_M_JenisBarang 'PP 3" SCH 40',''
exec sp_AddDLK_M_JenisBarang 'PP 3" SCH 80',''
exec sp_AddDLK_M_JenisBarang '15x10x100',''
exec sp_AddDLK_M_JenisBarang 'PS',''
exec sp_AddDLK_M_JenisBarang 'PRN 4',''
exec sp_AddDLK_M_JenisBarang 'KE 4',''
exec sp_AddDLK_M_JenisBarang 'RCK SA 1"',''
exec sp_AddDLK_M_JenisBarang 'RCK SA 4"',''
exec sp_AddDLK_M_JenisBarang 'SCK SA 1/2"',''
exec sp_AddDLK_M_JenisBarang 'SCK SA 1',''
exec sp_AddDLK_M_JenisBarang 'PP ALUM 5/8',''
exec sp_AddDLK_M_JenisBarang 'PP ALUM 1/2',''
exec sp_AddDLK_M_JenisBarang 'PP ALUM 3/8',''
exec sp_AddDLK_M_JenisBarang 'AL R134 3/8"',''
exec sp_AddDLK_M_JenisBarang 'PP 10 X 7',''
exec sp_AddDLK_M_JenisBarang 'PP 12 X 9',''
exec sp_AddDLK_M_JenisBarang 'RCK AW 1"',''
exec sp_AddDLK_M_JenisBarang 'RCK AW 4"',''
exec sp_AddDLK_M_JenisBarang 'RCK AW 4" 2',''
exec sp_AddDLK_M_JenisBarang 'RCK D 4"',''
exec sp_AddDLK_M_JenisBarang 'CR KH',''
exec sp_AddDLK_M_JenisBarang '15X30X1.4',''
exec sp_AddDLK_M_JenisBarang '15X30x1.7',''
exec sp_AddDLK_M_JenisBarang '20X40X1.1',''
exec sp_AddDLK_M_JenisBarang '20X20X1.4',''
exec sp_AddDLK_M_JenisBarang '20X40X1.7MM',''
exec sp_AddDLK_M_JenisBarang '30X30x1.4',''
exec sp_AddDLK_M_JenisBarang '30X30X1.1',''
exec sp_AddDLK_M_JenisBarang '30X30x1.4 2',''
exec sp_AddDLK_M_JenisBarang '30X30X1.7',''
exec sp_AddDLK_M_JenisBarang '30X60X1.4',''
exec sp_AddDLK_M_JenisBarang '30X60X1.7',''
exec sp_AddDLK_M_JenisBarang '40X40X2.3',''
exec sp_AddDLK_M_JenisBarang '40X40X2.3 2',''
exec sp_AddDLK_M_JenisBarang '40X40X1.7',''
exec sp_AddDLK_M_JenisBarang '40X80X1.7',''
exec sp_AddDLK_M_JenisBarang '30X30X1.2',''
exec sp_AddDLK_M_JenisBarang '40X20X1.4MM',''
exec sp_AddDLK_M_JenisBarang '40X40X1.1',''
exec sp_AddDLK_M_JenisBarang '40X40X2.2',''
exec sp_AddDLK_M_JenisBarang '40X60X1.7',''
exec sp_AddDLK_M_JenisBarang '40X60X1.4',''
exec sp_AddDLK_M_JenisBarang '40X60X2.0',''
exec sp_AddDLK_M_JenisBarang '40X60X2.0 2',''
exec sp_AddDLK_M_JenisBarang '40X60X2.8',''
exec sp_AddDLK_M_JenisBarang '40X80X2.2',''
exec sp_AddDLK_M_JenisBarang '50X100X2.3',''
exec sp_AddDLK_M_JenisBarang '50 X 50 X 3MM',''
exec sp_AddDLK_M_JenisBarang '60X30x1.7',''
exec sp_AddDLK_M_JenisBarang '1 X 1 1/2"',''
exec sp_AddDLK_M_JenisBarang '1 X 1"',''
exec sp_AddDLK_M_JenisBarang '38X38X3.8',''
exec sp_AddDLK_M_JenisBarang '80X80X8',''
exec sp_AddDLK_M_JenisBarang '28X28X2.8',''
exec sp_AddDLK_M_JenisBarang '40X40X3',''
exec sp_AddDLK_M_JenisBarang '38X38X2.3',''
exec sp_AddDLK_M_JenisBarang 'ZCM 0.75',''
exec sp_AddDLK_M_JenisBarang 'LB SS 0.8',''
exec sp_AddDLK_M_JenisBarang 'SB 4X25X2M',''
exec sp_AddDLK_M_JenisBarang 'SB 4X25X6M',''
exec sp_AddDLK_M_JenisBarang 'A0.8',''
exec sp_AddDLK_M_JenisBarang 'A1',''
exec sp_AddDLK_M_JenisBarang 'A1.2',''
exec sp_AddDLK_M_JenisBarang 'A1.2 2',''
exec sp_AddDLK_M_JenisBarang 'A1.2 3',''
exec sp_AddDLK_M_JenisBarang 'A1.2 4',''
exec sp_AddDLK_M_JenisBarang 'A1.5',''
exec sp_AddDLK_M_JenisBarang 'A1.8',''
exec sp_AddDLK_M_JenisBarang 'A1.8 2',''
exec sp_AddDLK_M_JenisBarang 'A2.5',''
exec sp_AddDLK_M_JenisBarang 'A2.8',''
exec sp_AddDLK_M_JenisBarang 'A4',''
exec sp_AddDLK_M_JenisBarang 'A5',''
exec sp_AddDLK_M_JenisBarang 'A5 2',''
exec sp_AddDLK_M_JenisBarang 'A6',''
exec sp_AddDLK_M_JenisBarang 'A6 2',''
exec sp_AddDLK_M_JenisBarang 'A6 3',''
exec sp_AddDLK_M_JenisBarang 'A12',''
exec sp_AddDLK_M_JenisBarang 'A8.0',''
exec sp_AddDLK_M_JenisBarang 'GAL 0.6',''
exec sp_AddDLK_M_JenisBarang ' GLV 0.8',''
exec sp_AddDLK_M_JenisBarang 'GVL 1MM',''
exec sp_AddDLK_M_JenisBarang 'GVL 1MM 2',''
exec sp_AddDLK_M_JenisBarang 'GAL 1',''
exec sp_AddDLK_M_JenisBarang 'BH 3',''
exec sp_AddDLK_M_JenisBarang 'BH 3 2',''
exec sp_AddDLK_M_JenisBarang 'BH 4',''
exec sp_AddDLK_M_JenisBarang 'BH 2.3',''
exec sp_AddDLK_M_JenisBarang 'AR',''
exec sp_AddDLK_M_JenisBarang 'CO2',''
exec sp_AddDLK_M_JenisBarang 'CO2 2',''
exec sp_AddDLK_M_JenisBarang 'O2',''
exec sp_AddDLK_M_JenisBarang 'O2 2',''
exec sp_AddDLK_M_JenisBarang 'C2H2',''
exec sp_AddDLK_M_JenisBarang 'LPG 12',''
exec sp_AddDLK_M_JenisBarang 'GN 145',''
exec sp_AddDLK_M_JenisBarang 'GN DN12.5',''
exec sp_AddDLK_M_JenisBarang 'GN 145.5',''
exec sp_AddDLK_M_JenisBarang 'GD D326',''
exec sp_AddDLK_M_JenisBarang 'GD S0261',''
exec sp_AddDLK_M_JenisBarang 'GD CR',''
exec sp_AddDLK_M_JenisBarang 'GD 24',''
exec sp_AddDLK_M_JenisBarang 'RGT CO',''
exec sp_AddDLK_M_JenisBarang '8MM',''
exec sp_AddDLK_M_JenisBarang '9',''
exec sp_AddDLK_M_JenisBarang '9 2',''
exec sp_AddDLK_M_JenisBarang '9 3',''
exec sp_AddDLK_M_JenisBarang '18',''
exec sp_AddDLK_M_JenisBarang '3',''
exec sp_AddDLK_M_JenisBarang 'SB 10',''
exec sp_AddDLK_M_JenisBarang 'SB 12',''
exec sp_AddDLK_M_JenisBarang 'A10',''
exec sp_AddDLK_M_JenisBarang 'TP 2MM',''
exec sp_AddDLK_M_JenisBarang 'KRT 2MM',''
exec sp_AddDLK_M_JenisBarang 'TP 1MM',''
exec sp_AddDLK_M_JenisBarang '3CM',''
exec sp_AddDLK_M_JenisBarang '4CM',''
exec sp_AddDLK_M_JenisBarang 'DPN PSA 55B',''
exec sp_AddDLK_M_JenisBarang 'ALCOPAN PE',''
exec sp_AddDLK_M_JenisBarang 'ALCOPAN PE 3MM',''
exec sp_AddDLK_M_JenisBarang 'YL 4',''
exec sp_AddDLK_M_JenisBarang 'LMT A3',''
exec sp_AddDLK_M_JenisBarang 'CTR BOX 2244',''
exec sp_AddDLK_M_JenisBarang 'CTR BOX 6464',''
exec sp_AddDLK_M_JenisBarang 'COR',''
exec sp_AddDLK_M_JenisBarang 'COR 2',''
exec sp_AddDLK_M_JenisBarang 'PE 10x25',''
exec sp_AddDLK_M_JenisBarang 'PE 10x25 2',''
exec sp_AddDLK_M_JenisBarang 'PE 12x30',''
exec sp_AddDLK_M_JenisBarang 'PE 14x35',''
exec sp_AddDLK_M_JenisBarang 'RAK 12LK',''
exec sp_AddDLK_M_JenisBarang 'PLK CC',''
exec sp_AddDLK_M_JenisBarang '35X50',''
exec sp_AddDLK_M_JenisBarang '35X50 2',''
exec sp_AddDLK_M_JenisBarang 'DR M14',''
exec sp_AddDLK_M_JenisBarang 'DR M16',''
exec sp_AddDLK_M_JenisBarang 'DR M18',''
exec sp_AddDLK_M_JenisBarang 'DR M22',''
exec sp_AddDLK_M_JenisBarang 'DB M24',''
exec sp_AddDLK_M_JenisBarang 'ST41 8',''
exec sp_AddDLK_M_JenisBarang 'ST41 16',''
exec sp_AddDLK_M_JenisBarang 'ST41 17',''
exec sp_AddDLK_M_JenisBarang 'ST41 10',''
exec sp_AddDLK_M_JenisBarang 'ST41 10 2',''
exec sp_AddDLK_M_JenisBarang 'ST41 10 3',''
exec sp_AddDLK_M_JenisBarang 'ST41 DIA 17',''
exec sp_AddDLK_M_JenisBarang 'ST41 30',''
exec sp_AddDLK_M_JenisBarang 'S45C 40MM',''
exec sp_AddDLK_M_JenisBarang 'S45C 50MM',''
exec sp_AddDLK_M_JenisBarang 'S45C 30MM',''
exec sp_AddDLK_M_JenisBarang 'S45C 16MM',''
exec sp_AddDLK_M_JenisBarang 'AS 16MM 3',''
exec sp_AddDLK_M_JenisBarang 'AS 16MM 4',''
exec sp_AddDLK_M_JenisBarang 'BCT',''
exec sp_AddDLK_M_JenisBarang 'BCT 2',''
exec sp_AddDLK_M_JenisBarang 'BPS 2MM',''
exec sp_AddDLK_M_JenisBarang 'BPS 2MM 2',''
exec sp_AddDLK_M_JenisBarang 'BWM 2MM',''
exec sp_AddDLK_M_JenisBarang 'BWM 2MM 2',''
exec sp_AddDLK_M_JenisBarang 'PSP',''
exec sp_AddDLK_M_JenisBarang 'PSP 2',''
exec sp_AddDLK_M_JenisBarang 'CCTV 12V 5A',''
exec sp_AddDLK_M_JenisBarang 'BP',''
exec sp_AddDLK_M_JenisBarang 'PLX',''
exec sp_AddDLK_M_JenisBarang 'HTM',''
exec sp_AddDLK_M_JenisBarang 'HTM 2',''
exec sp_AddDLK_M_JenisBarang 'ISL BKR 5',''
exec sp_AddDLK_M_JenisBarang 'ISL BKR 3',''
exec sp_AddDLK_M_JenisBarang 'ISL BKR 8',''
exec sp_AddDLK_M_JenisBarang 'ISL BKR 12',''
exec sp_AddDLK_M_JenisBarang 'DC',''
exec sp_AddDLK_M_JenisBarang 'BS DEX',''
exec sp_AddDLK_M_JenisBarang 'DC RED',''
exec sp_AddDLK_M_JenisBarang 'IS',''
exec sp_AddDLK_M_JenisBarang 'TRB 3084B J',''
exec sp_AddDLK_M_JenisBarang 'ISAR',''
exec sp_AddDLK_M_JenisBarang 'SPDX 1000X6000X0.3',''
exec sp_AddDLK_M_JenisBarang ' BJ 12MM',''
exec sp_AddDLK_M_JenisBarang 'S316',''
exec sp_AddDLK_M_JenisBarang 'ORCID',''
exec sp_AddDLK_M_JenisBarang 'LP',''
exec sp_AddDLK_M_JenisBarang 'PM',''
exec sp_AddDLK_M_JenisBarang 'CLN',''
exec sp_AddDLK_M_JenisBarang 'ACCE EP 175/65 R14',''
exec sp_AddDLK_M_JenisBarang 'DDK FSL',''
exec sp_AddDLK_M_JenisBarang 'DDK TL',''
exec sp_AddDLK_M_JenisBarang 'COM HD SD507',''
exec sp_AddDLK_M_JenisBarang 'CON HD UV14X18X19',''
exec sp_AddDLK_M_JenisBarang 'RD UV',''
exec sp_AddDLK_M_JenisBarang 'COM IT SD507',''
exec sp_AddDLK_M_JenisBarang 'CON IT FL',''
exec sp_AddDLK_M_JenisBarang 'COM HR FC508',''
exec sp_AddDLK_M_JenisBarang 'CON HR UV14X18X19',''
exec sp_AddDLK_M_JenisBarang 'REH',''
exec sp_AddDLK_M_JenisBarang 'MO 5',''
exec sp_AddDLK_M_JenisBarang 'BS SUZ SS 125 ORI',''
exec sp_AddDLK_M_JenisBarang 'RING SUZ SS 125 ORI',''
exec sp_AddDLK_M_JenisBarang 'KRT SUZ SS 125 ORI',''
exec sp_AddDLK_M_JenisBarang 'STRP MTR',''
exec sp_AddDLK_M_JenisBarang 'BHL BLKG',''
exec sp_AddDLK_M_JenisBarang 'HU 28',''
exec sp_AddDLK_M_JenisBarang 'HD 28',''
exec sp_AddDLK_M_JenisBarang 'BX',''
exec sp_AddDLK_M_JenisBarang 'ONDA',''
exec sp_AddDLK_M_JenisBarang 'USH 30X40X60',''
exec sp_AddDLK_M_JenisBarang 'LBH 30',''
exec sp_AddDLK_M_JenisBarang 'SEAL MANIFOUL',''
exec sp_AddDLK_M_JenisBarang '5MM',''
exec sp_AddDLK_M_JenisBarang '6MM',''
exec sp_AddDLK_M_JenisBarang 'B+K',''
exec sp_AddDLK_M_JenisBarang 'LM LOC',''
exec sp_AddDLK_M_JenisBarang '100K A',''
exec sp_AddDLK_M_JenisBarang '100K',''
exec sp_AddDLK_M_JenisBarang '50K',''
exec sp_AddDLK_M_JenisBarang 'GSR 10K',''
exec sp_AddDLK_M_JenisBarang 'GSR B10K MN',''
exec sp_AddDLK_M_JenisBarang 'GSR B10K STR',''
exec sp_AddDLK_M_JenisBarang '32A 3P',''
exec sp_AddDLK_M_JenisBarang '32A 3P 2',''
exec sp_AddDLK_M_JenisBarang 'BP6 GPOB ',''
exec sp_AddDLK_M_JenisBarang 'CH 410',''
exec sp_AddDLK_M_JenisBarang 'KTK UTN 4L',''
exec sp_AddDLK_M_JenisBarang ' BTN',''
exec sp_AddDLK_M_JenisBarang ' BTN 2',''
exec sp_AddDLK_M_JenisBarang '3M OV',''
exec sp_AddDLK_M_JenisBarang 'LG',''
exec sp_AddDLK_M_JenisBarang 'LD',''
exec sp_AddDLK_M_JenisBarang 'IJUK',''
exec sp_AddDLK_M_JenisBarang 'KNB',''
exec sp_AddDLK_M_JenisBarang 'DRAGON',''
exec sp_AddDLK_M_JenisBarang 'LNT',''
exec sp_AddDLK_M_JenisBarang 'PL',''
exec sp_AddDLK_M_JenisBarang 'DMI',''
exec sp_AddDLK_M_JenisBarang 'ST 2MM',''
exec sp_AddDLK_M_JenisBarang ' BE',''
exec sp_AddDLK_M_JenisBarang 'DGT 500G',''
exec sp_AddDLK_M_JenisBarang 'DGT',''
exec sp_AddDLK_M_JenisBarang 'TCT 305MM 12"',''
exec sp_AddDLK_M_JenisBarang 'EVO 355',''
exec sp_AddDLK_M_JenisBarang 'WGN 305',''
exec sp_AddDLK_M_JenisBarang 'MMA 500MM',''
exec sp_AddDLK_M_JenisBarang 'HRD',''
exec sp_AddDLK_M_JenisBarang 'FA RH',''
exec sp_AddDLK_M_JenisBarang 'FA LH',''
exec sp_AddDLK_M_JenisBarang 'CRL',''
exec sp_AddDLK_M_JenisBarang 'LTH',''
exec sp_AddDLK_M_JenisBarang 'DFR SG',''
exec sp_AddDLK_M_JenisBarang 'DRR SG',''
exec sp_AddDLK_M_JenisBarang 'HSG',''
exec sp_AddDLK_M_JenisBarang 'CTA',''
exec sp_AddDLK_M_JenisBarang 'UBA',''
exec sp_AddDLK_M_JenisBarang 'ELC',''
"
%>